/// @description vars 
// You can write your code in this editor
xTo = 0;
yTo = 0;
anglestart = 0;
angledistance = 0;
startx = 0;
starty = 0;
Timer = 60;
Beam = noone;
Interval = 0;
//audio_play_sound(gasterappear, 20, false); 
curve = animcurve_get_channel(gastercurve,"curve1");
DesAngle = 0;
percent = 0;
xTo = 0;
yTo = 0;
anglestart = 0;
angledistance = 0;
startx = 0;
starty = 0;
Spawned = false;
per_speed = 0;
destroy = false
end_time = 0;
depth = -2
shake = true;